# Generated by Django 4.1.7 on 2023-11-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=256)),
                ('text', models.TextField()),
                ('rank', models.IntegerField(db_index=True)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
