# Generated by Django 4.1.7 on 2024-01-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings_app', '0002_image_remove_category_is_featured_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='src',
            field=models.ImageField(default='default.jpg', upload_to='listing_images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
    ]
