# Generated by Django 4.1.7 on 2023-12-21 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings_app', '0002_alter_user_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
