# Generated by Django 4.1.7 on 2024-01-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings_app', '0003_remove_image_image_image_src_alter_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.ImageField(default='default.png', upload_to='listing_images/'),
        ),
    ]
