# Generated by Django 4.1.7 on 2024-01-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings_app', '0005_remove_listing_images_image_listing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
