# Generated by Django 4.1.7 on 2024-01-28 20:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings_app', '0006_alter_category_description_alter_listing_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings_app.listing', validators=[django.core.validators.FileExtensionValidator(['png'])]),
        ),
    ]
