FROM node:lts-alpine as build

WORKDIR /app

COPY frontend/package.json ./
COPY frontend/package-lock.json ./
RUN apk add --no-cache git && npm ci

COPY frontend /app
RUN npm run build

FROM node:lts-alpine AS production

WORKDIR /app

COPY --from=build /app/build ./build
COPY --from=build /app/package.json ./
COPY --from=build /app/package-lock.json ./

RUN npm ci --only=production

ENV HOST=0.0.0.0
ENV PORT=3000
EXPOSE 3000

CMD ["node", "build/index.js"]