FROM node:lts-alpine as runtime

COPY /frontend /app

WORKDIR /app

RUN npm install -g npm@10.2.5
RUN npm install
RUN npm run build


ENV HOST=0.0.0.0
ENV PORT=4321
EXPOSE 4321

CMD ["node", "dist/server/entry.mjs"]
