version: "3.9"

services:

  db:
    image: postgres:15-alpine3.18
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - "env-$RTE"

  djangoapp:
    image: registry.gitlab.com/noeldj/ms_listings_project/djangoapp:latest
    volumes:
      - media:/media/
      - static:/static/
    depends_on:
      - db
    env_file:
      - "env-$RTE"
    ports:
      - 8000:8000

  astroapp:
    image: registry.gitlab.com/noeldj/ms_listings_project/djangoapp:latest
    volumes:
      - media:/media/
      - static:/static/
    depends_on:
      - djangoapp

  nginx:
    image: nginx:latest
    volumes:
      - media:/media/
      - static:/static/
      - ./nginx/:/etc/nginx/conf.d/
    ports:
      - 80:4321
    depends_on:
      - astroapp

volumes:
  postgres_data:
  media:
  static:
