---
version: "3.9"

services:

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - "env_$RTE"

  djangoapp:
    image: registry.gitlab.com/noel100/ms_listings_web_application/djangoapp:latest
    volumes:
      - media:/app/media/
    depends_on:
      - db
    env_file:
      - "env_$RTE"

  svelteapp:
    image: registry.gitlab.com/noel100/ms_listings_web_application/svelteapp:latest
    volumes:
      - media:/app/media/
      - static:/static/
    depends_on:
      - djangoapp

  nginx:
    image: nginx:latest
    volumes:
      - media:/app/media/
      - ./nginx/:/etc/nginx/conf.d/
    ports:
      - 80:80
    depends_on:
      - svelteapp
      - djangoapp

volumes:
  postgres_data:
  media:
  static:
