FROM node:lts-alpine AS build

WORKDIR /app

COPY frontend/package.json frontend/package-lock.json ./

RUN apk --no-cache add --virtual .gyp python make g++
RUN npm install --only=production

COPY frontend/ .

RUN npm run build

FROM node:lts-alpine AS production

WORKDIR /app

COPY --from=build /app/build ./build
COPY --from=build /app/package.json /app/package-lock.json ./

RUN npm ci --only=production

ENV HOST=0.0.0.0
ENV PORT=3000
EXPOSE 3000

CMD ["node", "build/index.js"]