version: "3.9"

services:

  db:
    image: postgres:15-alpine3.18
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - "env-$RTE"

  djangoapp:
    image: registry.gitlab.com/noeldj/ms_listings_project/djapp:latest
    volumes:
      - media:/media/
      - static:/static/
    depends_on:
      - db
    env_file:
      - "env-$RTE"

  nginx:
    image: nginx:latest
    volumes:
      - media:/media/
      - static:/static/
      - ./nginx/:/etc/nginx/conf.d/
    ports:
      - 80:8000

volumes:
  postgres_data:
  media:
  static:

