FROM python:3.10-alpine

ENV PYTHONUNBUFFERED=1 
ENV PYTHONDONTWRITEBYTECODE=1

RUN apk add python3-dev postgresql-client postgresql-dev musl-dev build-base

COPY /backend /app
COPY ./entrypoint-django-app.sh /app
WORKDIR /app

RUN python -m venv .venv && \
    source .venv/bin/activate && \
    pip install --upgrade pip && \
    pip install -r requirements.txt

ENTRYPOINT ["sh", "entrypoint-django-app.sh"]