---
version: "3.9"

services:

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - "env_$RTE"

  djangoapp:
    image: registry.gitlab.com/noel100/ms_listings_web_application/djangoapp:latest
    volumes:
      - media:/media/
      - static:/static/
    depends_on:
      - db
    env_file:
      - "env_$RTE"
    ports:
      - 8000:8000

volumes:
  postgres_data:
  media:
  static:
