FROM node:lts-alpine as runtime

WORKDIR /app

COPY /frontend /app

RUN npm install -g npm@10.2.5 && \
    npm install && \
    npm run build

ENV HOST=0.0.0.0
ENV PORT=4321
EXPOSE 4321

CMD ["node", "dist/server/entry.mjs"]
