---
version: "3.9"

services:

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - "env_$RTE"

  djangoapp:
    image: djangoapp:latest
    volumes:
      - media:/media/
      - static:/static/
    depends_on:
      - db
    env_file:
      - "env_$RTE"
    ports:
      - 8000:8000

  astroapp:
    image: astroapp:latest
    volumes:
      - media:/media/
      - static:/static/
    depends_on:
      - djangoapp

  nginx:
    image: nginx:latest
    volumes:
      - media:/media/
      - static:/static/
      - ./nginx/:/etc/nginx/conf.d/
    ports:
      - 80:3000
    depends_on:
      - astroapp

volumes:
  postgres_data:
  media:
  static:
