version: "3.9"

services:

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - env

  djangoapp:
    image: djangoapp:latest
    volumes:
      - media:/media/
      - static:/static/
    depends_on:
      - db
    env_file:
      - env
    ports:
      - 8000:8000

  astroapp:
    image: astroapp:latest
    volumes:
      - media:/media/
      - static:/static/
    ports:
      - 4321:4321

volumes:
  postgres_data:
  media:
  static:
